# ..air.toml
root = "."
tmp_dir = "tmp"

[run]
envs_bin = ["CELERIX_NAMESPACE=c01e6180-2026-4d21-828a-7239842a2222"]

[build]
# We build from the root, pointing to the backend main file
cmd = "go build -o ./tmp/main ./cmd/flow/main.go"
entrypoint = "./tmp/main"
# Watch only the backend folder for Go changes
#include_dir = ["backend"]
exclude_dir = ["frontend", "tmp", "data", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html", "json"]
delay = 1000
stop_on_error = true
log = "air.log"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
log = "white"

[screen]
clear_on_rebuild = true